name: Qualify Code based on uv (reusable)
permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-common-uv-qualify:
    strategy:
      fail-fast: false # いずれかのバージョンで失敗しても他のバージョンの実行を継続する
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    uses: Seika139/.github/.github/workflows/uv-qualify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
